CREATE DATABASE IF NOT EXISTS eukasko CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE eukasko;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  phone VARCHAR(60) DEFAULT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  admin_note TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS quotes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT DEFAULT NULL,
  session_key VARCHAR(120) DEFAULT NULL,
  year INT NOT NULL,
  brand VARCHAR(120) NOT NULL,
  model VARCHAR(120) NOT NULL,
  vin VARCHAR(40) DEFAULT NULL,
  plate VARCHAR(40) DEFAULT NULL,
  car_value DECIMAL(12,2) NOT NULL,
  experience INT NOT NULL DEFAULT 0,
  driver_name VARCHAR(190) DEFAULT NULL,
  driver_birth DATE DEFAULT NULL,
  driver_license VARCHAR(120) DEFAULT NULL,
  car_doc_path VARCHAR(255) DEFAULT NULL,
  driver_doc_path VARCHAR(255) DEFAULT NULL,
  deductible INT NOT NULL DEFAULT 15000,
  opt_theft TINYINT(1) NOT NULL DEFAULT 0,
  opt_glass TINYINT(1) NOT NULL DEFAULT 0,
  opt_road TINYINT(1) NOT NULL DEFAULT 0,
  brand_class VARCHAR(30) NOT NULL,
  price_year DECIMAL(12,2) NOT NULL,
  price_month DECIMAL(12,2) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'new',
  admin_note TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT NULL,
  CONSTRAINT fk_quotes_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS policies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  policy_number VARCHAR(50) NOT NULL UNIQUE,
  quote_id INT DEFAULT NULL,
  user_id INT DEFAULT NULL,
  holder_email VARCHAR(190) NOT NULL,
  holder_phone VARCHAR(60) NOT NULL,
  plan VARCHAR(30) NOT NULL,
  promo VARCHAR(50) DEFAULT NULL,
  admin_note TEXT DEFAULT NULL,
  total_year DECIMAL(12,2) NOT NULL,
  total_month DECIMAL(12,2) NOT NULL,
  method VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  start_date DATE NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT NULL,
  CONSTRAINT fk_policies_quotes FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE SET NULL,
  CONSTRAINT fk_policies_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS receipts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  receipt_number VARCHAR(50) NOT NULL UNIQUE,
  policy_id INT DEFAULT NULL,
  user_id INT DEFAULT NULL,
  payment_method VARCHAR(30) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  month_amount DECIMAL(12,2) NOT NULL,
  card_last4 VARCHAR(4) DEFAULT NULL,
  card_exp VARCHAR(10) DEFAULT NULL,
  payer_email VARCHAR(190) DEFAULT NULL,
  payer_phone VARCHAR(60) DEFAULT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'paid',
  admin_note TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT NULL,
  CONSTRAINT fk_receipts_policies FOREIGN KEY (policy_id) REFERENCES policies(id) ON DELETE SET NULL,
  CONSTRAINT fk_receipts_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS claims (
  id INT AUTO_INCREMENT PRIMARY KEY,
  claim_number VARCHAR(50) NOT NULL UNIQUE,
  policy_id INT DEFAULT NULL,
  user_id INT DEFAULT NULL,
  claim_type VARCHAR(80) NOT NULL,
  claim_date DATE NOT NULL,
  description TEXT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'received',
  admin_note TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT NULL,
  CONSTRAINT fk_claims_policies FOREIGN KEY (policy_id) REFERENCES policies(id) ON DELETE SET NULL,
  CONSTRAINT fk_claims_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS responses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(40) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'new',
  user_id INT DEFAULT NULL,
  name VARCHAR(160) DEFAULT NULL,
  email VARCHAR(190) DEFAULT NULL,
  phone VARCHAR(60) DEFAULT NULL,
  subject VARCHAR(255) DEFAULT NULL,
  message TEXT DEFAULT NULL,
  quote_id INT DEFAULT NULL,
  policy_id INT DEFAULT NULL,
  claim_id INT DEFAULT NULL,
  receipt_id INT DEFAULT NULL,
  attachment_path VARCHAR(255) DEFAULT NULL,
  admin_note TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT NULL,
  CONSTRAINT fk_responses_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_responses_quotes FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE SET NULL,
  CONSTRAINT fk_responses_policies FOREIGN KEY (policy_id) REFERENCES policies(id) ON DELETE SET NULL,
  CONSTRAINT fk_responses_claims FOREIGN KEY (claim_id) REFERENCES claims(id) ON DELETE SET NULL,
  CONSTRAINT fk_responses_receipts FOREIGN KEY (receipt_id) REFERENCES receipts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
